import Head from 'next/head';
import HomePage from './home';
// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyDYYQjhHNrILVPC2_JkIn_4xkpj481u0LY",
  authDomain: "fir-project-152cf.firebaseapp.com",
  projectId: "fir-project-152cf",
  storageBucket: "fir-project-152cf.firebasestorage.app",
  messagingSenderId: "56768052108",
  appId: "1:56768052108:web:9eadcdaba73275ea1074a9"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
export default function Home() {
  return (
    <>
      <Head>
        <title>Real Estate </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <HomePage />
        </div>
      </main>
    </>
  );
}
